language: python
sudo: required
services:
- docker
before_install:
- docker pull thejodesterf5/containthedocs
script:
- ./scripts/docker-docs.sh ./scripts/test-docs.sh
deploy:
  - provider: s3
    access_key_id:
      secure: "Ii+nwaFHk5XBlHKOT9RcK65T/rYpT1ZUEf+q+5MwUBbhgbkhLo75pyTxRLJNNNR/apDcjV4gFa/WyQsnqei/EbKcXLCVMZgdd0bBzoB8iG9DJmzybuPmqMcxP2yxjAzZWNMbPkeiRchtfcgYPd0EICRjBLaH0VTUS+gBzr6WbUvKH2/sM85FNOaZR5qW7l8122D/cvU8PKYtSR/saTHUa75mrry4AyvTs3CzrZzAFrUT4qBUST0XvMv/vwTTMVo708y5ViEsE4oXkfjbXhy14p/hNoU9kU10TvZZJ3k0VJqs5KQsu+IA2TRcLRJxEQa9OoctcC4Mf+88o9svjOeMYBS/whdiecGdQgmy2hWNvs5ZcwwqIFo6agRW41gTBMBm5fk9UueXfy/8DXtXmvt9wW0+ItX5CK9OS2yStw3fsdN+MF0vQmx0qv7RftxUSB97oee8YxF8mwvRQJEYg8Wqj199Liz/6EGFcCwBezolvjXtJSHQry9blRQkTC/+PFsHP5nfwxzDJ5DmjI8E2WkuMh1vDvMJz6jzGGai0Gu2UFiPVZRSZPkIxFgwYzKBMFfZcWI9tYm1rnsTGIgnc7gVW4aU5GoYLQIuYhTapNDQcDeGzwIgh1TsYJgKAPuaeIKNbvwW4aAKsE3jUFzJA/2OarHdCECSGVZyXMtwt6X4Dgg="
    secret_access_key:
      secure: "ePpWERNloDP7vWz9On0zMngpMKwtRte6fi0SLRDKy0EYyhjWJVutBZnyJRstulpZ4TnYQEKB4hjSbjjdxdLVBf0PeJcXgN8O7ePsbbh171P+L+ktZNm/3KB2/xXPvOA8Ezwu1JRe/nxHXWUCKuqn3rZB0pB9/xqq+ajC7D3kFDhZQsaItj5hXCAIelJEbXgHoXgnd/x119m30U/rNqFGLCkaygote9eOmMUCtHB888uip7kQkXDbrglzsWVI6/Ed7YG6udT2QT6xH6o9lpc4F0ILl/7qC4s69/k2gmSfKtLJCpdK8h7M7HMrbSePTc5XZpdXcs0/67asCarICIngCyihIywgBcMm0KE7hxwouF09AzL6pyJeEYcv3PSmbamiWV8XBBXnuEifADZ7o1ouH/IrQvo2y+k0FpgBlOu2sD/1cX2vXP+Ngsa6QPM8RNqRvC4ReajbUGapkpm5O3JwbHotHI3DqzmH7rxwya55LRsXe639XfFsRZP7AxteRADt4W968ekyTPx1WJiDCw5x0b0l0Mci8TcsuiBCtmLfQ7mvVNbrTmIFa4wG6n1XyjSzCWlB4Yoj8AvJhERm8AlMW59nN+4kO34owgs0gFLWjkiWZQS+xY+FKiZ4wpuaZOvmEKgSLD35Njei3rLQfuHf0prSU8fvbViTb6o0fgdZGVc="
    bucket: $S3_BUCKET_NAME
    local-dir: docs/_build/html
    upload-dir: containers/$TRAVIS_TAG
    skip-cleanup: true
    region: "us-west-2"
    on:
      tags: true
  - provider: s3
    access_key_id:
      secure: "Ii+nwaFHk5XBlHKOT9RcK65T/rYpT1ZUEf+q+5MwUBbhgbkhLo75pyTxRLJNNNR/apDcjV4gFa/WyQsnqei/EbKcXLCVMZgdd0bBzoB8iG9DJmzybuPmqMcxP2yxjAzZWNMbPkeiRchtfcgYPd0EICRjBLaH0VTUS+gBzr6WbUvKH2/sM85FNOaZR5qW7l8122D/cvU8PKYtSR/saTHUa75mrry4AyvTs3CzrZzAFrUT4qBUST0XvMv/vwTTMVo708y5ViEsE4oXkfjbXhy14p/hNoU9kU10TvZZJ3k0VJqs5KQsu+IA2TRcLRJxEQa9OoctcC4Mf+88o9svjOeMYBS/whdiecGdQgmy2hWNvs5ZcwwqIFo6agRW41gTBMBm5fk9UueXfy/8DXtXmvt9wW0+ItX5CK9OS2yStw3fsdN+MF0vQmx0qv7RftxUSB97oee8YxF8mwvRQJEYg8Wqj199Liz/6EGFcCwBezolvjXtJSHQry9blRQkTC/+PFsHP5nfwxzDJ5DmjI8E2WkuMh1vDvMJz6jzGGai0Gu2UFiPVZRSZPkIxFgwYzKBMFfZcWI9tYm1rnsTGIgnc7gVW4aU5GoYLQIuYhTapNDQcDeGzwIgh1TsYJgKAPuaeIKNbvwW4aAKsE3jUFzJA/2OarHdCECSGVZyXMtwt6X4Dgg="
    secret_access_key:
      secure: "ePpWERNloDP7vWz9On0zMngpMKwtRte6fi0SLRDKy0EYyhjWJVutBZnyJRstulpZ4TnYQEKB4hjSbjjdxdLVBf0PeJcXgN8O7ePsbbh171P+L+ktZNm/3KB2/xXPvOA8Ezwu1JRe/nxHXWUCKuqn3rZB0pB9/xqq+ajC7D3kFDhZQsaItj5hXCAIelJEbXgHoXgnd/x119m30U/rNqFGLCkaygote9eOmMUCtHB888uip7kQkXDbrglzsWVI6/Ed7YG6udT2QT6xH6o9lpc4F0ILl/7qC4s69/k2gmSfKtLJCpdK8h7M7HMrbSePTc5XZpdXcs0/67asCarICIngCyihIywgBcMm0KE7hxwouF09AzL6pyJeEYcv3PSmbamiWV8XBBXnuEifADZ7o1ouH/IrQvo2y+k0FpgBlOu2sD/1cX2vXP+Ngsa6QPM8RNqRvC4ReajbUGapkpm5O3JwbHotHI3DqzmH7rxwya55LRsXe639XfFsRZP7AxteRADt4W968ekyTPx1WJiDCw5x0b0l0Mci8TcsuiBCtmLfQ7mvVNbrTmIFa4wG6n1XyjSzCWlB4Yoj8AvJhERm8AlMW59nN+4kO34owgs0gFLWjkiWZQS+xY+FKiZ4wpuaZOvmEKgSLD35Njei3rLQfuHf0prSU8fvbViTb6o0fgdZGVc="
    bucket: $S3_BUCKET_NAME
    local-dir: docs/_build/html
    upload-dir: containers/$TRAVIS_BRANCH
    skip-cleanup: true
    region: "us-west-2"
    on:
      all_branches: true
notifications:
  slack:
    secure: JPfhrjoJMHIolWfr+BggymfsuzcMq8hQrI6NgmbH9Op/1LnP7v0pzXabvePBX6jCzEpB6E/pizwrw/7D5r78+GD6gm2eiZ3NNupBSnVBwSQr51pfAH23RB1pafTgjyllrNJLAWia23ihB1oa+yj3ll/clOXke5o8436IJp+KRUk0q8F0HBbke7lLcGii/H2WqGZ9f6bqee0w6wVCjKL86o5EjbF/muBScw6npeGAyuShILsUybgQwJnCHG2Vn4o4L+ZzGga8FljhUJxEIx4v+m0wwTg7mIRrLQbZ0qCXQfc8hU858koa5+nVTt9Cj3fiLNIOtd0K6RujwTqdPTSMBrpbs7Gr1wzaejaKYsWUeJ1DG75MfpbHhTuUgNHNktgEVU6xiS8NL3RwsqfzU6vLbwe2e1EmAOQN6mTKkD+QU3dtJCPHr1tDydN5BSt+uVrd2EiGGuQMIfLGSPBJgCieu0dHgCAKOArKU0zn/gHJhwjxBALq2w0G75JR/wzz7agyQ4awCYZy866hLJPAMKtk+6Bl9qvmKfWBaXQDqrRpZBlhQqOKz2BL/wLPsP3/fVdubn98Ip3ZiTbXmxSRfNCCk4URsx1k9iWk9Qxs+oXIgBfvXuOJxAuwG7OYSbu6HCf18FbaZ2dmkU2hjicEL3BThHjWwf7V4aNdbtanJqkbh6s=
