language: python
sudo: required
services:
- docker
before_install:
- docker pull thejodesterf5/containthedocs
script:
- ./scripts/docker-docs.sh ./scripts/test-docs.sh
- sudo rm -rf docs/_build/linkcheck
deploy:
- provider: s3
  access_key_id:
    secure:
  secret_access_key:
    secure:
  bucket: $S3_BUCKET_NAME
  local-dir: docs/_build/
  upload-dir: containers/$TRAVIS_BRANCH
  skip-cleanup: true
  region: us-west-2
  on:
    branch: $TRAVIS_BRANCH
    condition: $TRAVIS_PULL_REQUEST = false
- provider: s3
  access_key_id:
    secure: 
  secret_access_key:
    secure: 
  bucket: $S3_BUCKET_NAME
  local-dir: docs/_build/
  upload-dir: containers/$TRAVIS_TAG
  skip-cleanup: true
  region: us-west-2
  on:
    tags: true
notifications:
  slack:
    secure: WJtWoSB8LMb2EuKVzlVt0LB2FJMocWrXRpT0IKhx4143wjQyZUmZtk6lzX0a/CtMI9JqhJy/fWawHAyEDJrpr2VWoahGlxc1c5+3tOfhnM62s3i3bZC/FCsXffs4O9Fci6eFeiw/300q1oQu3nvRj2rntmSXwB5Dp68vMnvvevttseljwWCYocxmN3CFBcfT3+0LU+LRQOz/WdP/DWoQqBD0rcvVnxpBx/1MMtDp2q55tCzJTukLQbIRCY/Onz+Hc/ZXYmbK+yIu5/N0Ylbhu0hwdXD0vJrrxSt68MjxReuM4U6aF3vC4QZ7d87bxTNKBKnGd/+KNnB5rbLsJyeHjI0f6Qx90MpP71PSIF3eQl1g7pC3hrsb/UP9iEpVeC6Hb9vM7J9U67WJckEty19Rwwlw0Bgiem52JMq+cctX/THCTTe9X87PHGtItDsRc4C3xoonSigaaiuh1/wh3Tabx8RYNZaWOoHUv5M3G50V7zszYF0427n0S0ckfHZ0bcVlU+TLAVhv0XWueoK3ggTE08NV+g2oFiPG88fKiKNIJxSzap4a2qEBELIUJUuYLn7FA4x3isEQVpbikocaPuXRm7060Q1oBv8tDPVkDWaQS3QnqknvDQGGL9MvrB1ZSjiASG0Saw7HYauNWxFxgxLPpsjk2+InYcj3wL6KEo8G0bs=
